services:
  app:
    build: .
    container_name: rate_limiter_app
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}

      RATE_LIMIT_IP: ${RATE_LIMIT_IP}
      RATE_LIMIT_TOKEN_DEFAULT: ${RATE_LIMIT_TOKEN_DEFAULT}
      BLOCK_DURATION_SECONDS: ${BLOCK_DURATION_SECONDS}
    restart: unless-stopped
  redis:
    image: redis:7
    container_name: rate_limiter_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  redis_data: